name: workflow to deploy an ARM Template using CLI commands
on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS
# 2. Change these variables for your configuration:

env:
  AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name  
  AZURE_LOCATION: WestEurope  # set this to your Location Name 
  AZURE_TEMPLATE: $GITHUB_WORKSPACE/azuredeploy.json  # Provide the file name to the template

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
                
    # Authentication
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template
    - name: Azure CLI script to deploy an ARM Template
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP }}
          az group deployment create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file ${{ env.AZURE_TEMPLATE }}
