name: trigger_scan_on_scope_secret
on:
  push:
    paths:
    - '**trigger-scan-on-scope-secret.yml'

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: ${{secrets.SCAN_SCOPE}}
