name: "Terraform Deploy"
on:
  push:
    branches:
      - master

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

# For terraform sample templates, refer to https://github.com/Azure/terraform/tree/master/samples

env:
  TF_VER: 0.12.29
  TF_WORKING_DIR: "terraform2" # "terraform_templates"
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VER }}

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}

      - name: "Terraform Apply"
        id: apply
        run: terraform apply
        env:
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples